apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-6-deployment
  namespace: student-6

spec:
  selector:
    matchLabels:
      app: student-6
  template:
    metadata:
      labels:
        app: student-6
    spec:
      containers:
      - name: student-6
        image: registry.tanzu.dk/ops2devops/student-6:v1
