apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-6-deployment
  namespace: student-6
spec:
  selector:
    matchLabels:
      app: student-6
  template:
    metadata:
      labels:
        app: student-6
    spec:
      containers:
      - name: student-6
        image: registry.tanzu.dk/ops2devops/studentx:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student-6
spec:
  type: NodePort
  selector:
    app: student-6
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30016

